version: '3.8'

services:
  postgres:
    container_name: db-journey
    image: postgres:16.2-alpine3.19
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - network-journey

  api:
    container_name: api-journey
    build: .
    ports:
      - 3333:3333
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - API_BASE_URL=${API_BASE_URL}
      - WEB_BASE_URL=${WEB_BASE_URL}
      - PORT=${PORT}
    depends_on:
      - postgres
    networks:
      - network-journey

networks:
  network-journey:
    driver: bridge