name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    name: 'Build image and publish into ghcr'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate sha
        id: generate_sha
        run: |
          SHA=$(echo $GITHUB_SHA | head -c7)
          echo "sha=${SHA}" >> $GITHUB_OUTPUT

      - name: Build docker image
        run: docker build -t ghcr.io/igorserafim/nlw.journey.api:${{ steps.generate_sha.outputs.sha }} .

      - name: Log into the container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
  
      - name: Push image
        run: |
          docker push ghcr.io/igorserafim/nlw.journey.api:${{ steps.generate_sha.outputs.sha }}
          docker tag ghcr.io/igorserafim/nlw.journey.api:${{ steps.generate_sha.outputs.sha }} ghcr.io/igorserafim/nlw.journey.api:latest
          docker push ghcr.io/igorserafim/nlw.journey.api:latest
