name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build docker image
        run: docker build -t igorserafim/nlw.journey.api:latest .
